name: Auto Commit

on:
  workflow_run:
    workflows: ["docker"]
    types:
      - completed

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Auto-commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto commit tras ejecución de Docker"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
          skip_dirty_check: true
